### ISSUE TITLE
Jupyter Notebook Links 

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW-ReportCard-Data#13]
We currently link to the [All Programs ](https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Cross-Program/blob/master/AllPrograms.ipynb)and [National](https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Cross-Program/blob/master/ECHO_National.ipynb) notebooks throughout the report. 
Wanted to check in and make sure that these were still good to go. Really I'm worried about national since it looks like it hasn't been maintained since 9/24/2020. Can I just get a general thumbs up or thumbs down that these are ok for folks to use right now ?

**Comment by ericnost** [comment]
@mraisle We will need to update National and re-run if we do 2020 stats, but otherwise it should be fine.

The one thing you need to change in both links is that they should point to .../main/... instead of .../master/.... The latest versions of both notebooks will be found at main rather than master. Does that make sense?

**Comment by mraisle** [comment]
Yep, that makes sense. Thank you! Went ahead and made the master --> main switch.

@shansen5 Correct me if this is wrong .  . . but I think we are already doing 2020 stats in places in the report so yes would be good to update National.

**Comment by ericnost** [comment]
@mraisle I can update the National ipynb (should be pretty easy, just switch all instances of 2019 to 2020) but I'm not sure if that will change anything in the report card generation process - It's still not clear to me what role the notebooks themselves play there.

**Comment by mraisle** [comment]
It won't change anything in the reportcard generation process! Just good to keep the notebook up to date with the reportcards. Thank you!

**Comment by ericnost** [comment]
Cool - I'll make the change in the NB tomorrow
