### ISSUE TITLE
Legislator Photos Not Up to Date

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW-ReportCard-Data#15]
Ran a random report as a test . . .turned out to be Cori Bush and it looks like legislator pictures have not been updated since new term (see below). Do we have to update these by hand? I remember when Cole and I did it but not sure if you have a new system @shansen5 .

![Screen Shot 2021-08-22 at 1 30 49 PM](https://user-images.githubusercontent.com/50874611/130364453-2fe0f783-7dcf-48c1-bb05-dd7f8652d38f.png)

**Comment by shansen5** [comment]
I hadn't checked in the corrected images.
