### ISSUE TITLE
Rmd - Put facility numbers in the maps

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/EEW-ReportCard-Data#2]
The maps currently cannot be generated in the Digital Ocean droplet (although that hasn’t been tried).  The maps now show the district or state without any facility numbers.  The facility numbers will change monthly.
Can we programmatically overlay the CWA/CAA/RCRA facility numbers on the map within the Rmd?
Should we just show the state/district map as is, without numbers?
Could we list the numbers beside or below the map?

**Comment by mraisle** [comment]
Solved! Utilizes CSS and call to region db that you (Steve) created to get facility numbers for the individual program pages (get_active_facilities). Demo [here](https://edgi-govdata-archiving.github.io/CD-report/front_page). Updated css is merged to main and will merge with template tomorrow and push.
In process of doing this . .  .realized that this might not even by that helpful of information? Ie - if someone comes to the report and doesn't know what these programs or numbers mean but it's displayed on the first page? Potentially confusing and/or not helpful info.
