### ISSUE TITLE
Rmd - graphs and tables

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/EEW-ReportCard-Data#6]
Layout tweaks are needed on several of the graphics

**Comment by mraisle** [comment]
Enforcement Actions graph on highlights page (page 3) was not displaying b/c a change in column name in a different dataframe was causing y-axis to not have a range. Solved and will push with other changes today.

**Comment by mraisle** [comment]
Other Fixes I'm working on 

- ~~Re-organize system of presidential year column so column # is irrelevant (using mutate)~~
- Create set-up for Biden data (some 2021 data should be present for CWA but it doesn't appear to be yet? can't test until resolved) 
- Fix formatting on non-compliance page to account for <10 facilities and make sure text aligns with figure
- Change logic on enforcement actions graphs for individual program pages - currently set to 1.2x number of violations to show discrepancy when there are (usually) few actions compared to violations, but values are hidden when actions > violations. 
- Modify Steve's if function for 0 count on program pages (ie ~line 780 for CAA)
- Fix President axis problems on program pages: ~~CAA~~, CWA, RCRA
