### ISSUE TITLE
Rmd - State_template.rmd needed

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/EEW-ReportCard-Data#7]
After fixes are made to the CD_template.rmd we need to get them incorporated into one for the states/senators.  An earlier version of such a template is in meg_files/senator_template.rmd.

**Comment by ericnost** [comment]
Also adding @mraisle here, though I know her capacity to adjust the template will be limited.

**Comment by mraisle** [comment]
@ericnost Working on it :)
