### ISSUE TITLE
Transfer the Digital Ocean droplet into an account owned by EDGI

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/EEW-ReportCard-Data#8]
The plan was increased from the base (1GB memory @ $5/month) to 4GB memory @ $20/month.  This was needed to build some of the R libraries needed.  Now that they are built we might be able to scale back to 2GB @ $10/month.
Test the idea of scaling it back.
This should be done by 9/26, as credits are good through that date.  (EDGI should get 2 months to use $100 credit when it creates an account.)

**Comment by ericnost** [comment]
@shansen5 I've created EDGI's Digital Ocean account. 

The steps to transfer and accept a droplet are overviewed here: https://docs.digitalocean.com/support/How-do-I-transfer-a-Droplet-to-another-user/

1. You need to create a snapshot of your droplet: https://docs.digitalocean.com/products/images/snapshots/quickstart/
2. Then you can transfer it to the EDGI user (envirodgi@gmail.com): https://docs.digitalocean.com/products/images/snapshots/how-to/change-owners/
3. I won't be notified once you've transferred it, so just let me know here or on Slack. This is the process I'll go through to accept the snapshot and create a new one from it: https://docs.digitalocean.com/products/images/snapshots/how-to/change-owners/#receiving-a-snapshot
